kind: List
apiVersion: v1
items:
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfig
  metadata:
    labels:
      machineconfiguration.openshift.io/role: worker
    name: disable-ipi-infra-compute
  spec:
    config:
      ignition:
        config: {}
        security:
          tls: {}
        timeouts: {}
        version: 3.2.0
      networkd: {}
      passwd: {}
      storage:
        files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,
          mode: 420
          overwrite: true
          path: /etc/kubernetes/manifests/keepalived.yaml
        - contents:
            source: data:text/plain;charset=utf-8;base64,
          mode: 420
          overwrite: true
          path: /etc/kubernetes/manifests/coredns.yaml        
    osImageURL: ""
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfig
  metadata:
    labels:
      machineconfiguration.openshift.io/role: master
    name: disable-ipi-infra-cp
  spec:
    config:
      ignition:
        config: {}
        security:
          tls: {}
        timeouts: {}
        version: 3.2.0
      networkd: {}
      passwd: {}
      storage:
        files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,
          mode: 420
          overwrite: true
          path: /etc/kubernetes/manifests/haproxy.yaml
        - contents:
            source: data:text/plain;charset=utf-8;base64,
          mode: 420
          overwrite: true
          path: /etc/kubernetes/manifests/keepalived.yaml
        - contents:
            source: data:text/plain;charset=utf-8;base64,
          mode: 420
          overwrite: true
          path: /etc/kubernetes/manifests/coredns.yaml        
    osImageURL: ""